### ISSUE TITLE
Is redmine_telegram_common actually a requirement?

### ISSUE THREAD

**Issue by kostajh** [centosadmin/redmine_2fa#18]
Hi! Thanks for this wonderful plugin.

I'm using it only for Google Authenticator functionality. The plugin seems to work just fine without installing `redmine_telegram_common`. I just wanted to confirm that I'm not missing something. Perhaps the README could be updated to indicate that `redmine_telegram_common` is a requirement only if you want to use the Telegram auth functionality?

**Comment by arturtr** [comment]
It is required for `OtpBotWebhookController`. It needs only for telegram, but rails loads this controller (with other controllers) on rails start.

You can try to remove `redmine_telegram_common`, but I think that you'll catch `Uninitialized constant` error after it.
But you can try :)
