### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by imaia** [centosadmin/redmine_2fa#19]
SyntaxError: /usr/src/redmine/plugins/redmine_2fa-master/lib/redmine_2fa/code_sender.rb:19: syntax error, unexpected '.' case user&.auth_source&.auth_method_name

**Comment by arturtr** [comment]
Upgrade your ruby to 2.3

**Comment by imaia** [comment]
Thanks, @arturtr Latest redmine docker image still uses ruby 2.2. I sent them a PR to version bump it. Let's see how it goes.
