### ISSUE TITLE
Allow multiple 2FA methods per account

### ISSUE THREAD

**Issue by kostajh** [centosadmin/redmine_2fa#25]
It would be really nice if one could associate multiple 2FA methods with a single account, like on GitHub. So as a user, I could set up SMS, Telegram, and Google Auth; when prompted to login, I could pick which method I would like to use for second factor authentication.

**Comment by constXife** [comment]
Thanks for you suggestion! Sorry, we doesn't have a plan to do it right now. But we will glad to see any pull requests.
