### ISSUE TITLE
2FA with LDAP doesn't work

### ISSUE THREAD

**Issue by romansavrulin** [centosadmin/redmine_2fa#27]
Hello! we are using LDAP authentication scheme and decidet to add 2FA with your plugin. It seems to be impossible to achieve, because user can be set to use either one of plugin method, or internal or LDAP.

Can we do some workaround to make it work?

**Comment by constXife** [comment]
Hi! Yes, at now there is no way to use 2fa with another auth source. We made expiremental support of other auth sources, but we need to test it. If you want to take a part in this then

1. Update 2fa plugin from ldap branch
2. Update redmine_telegram_common plugin from ldap branch
3. Run 2fa migrations
4. Run bundle exec rake redmine_2fa:common:remove_auth_source
5. Use plugin like usual, but now 2fa will respect your auth source choice

I recommend you to make database backup before update.

**Comment by romansavrulin** [comment]
@constXife That's great! Thank you! But I'm not sure I will have enough time to experiment with that in near future. As for now we rejected redmine usage in favor to Gitlab.com

**Comment by constXife** [comment]
Ah, I see. It's ok! And we are sorry for so long response. :( Good luck with Gitlab!
