### ISSUE TITLE
Инициализация бота: Redmine 500 error

### ISSUE THREAD

**Issue by muradurm** [centosadmin/redmine_2fa#28]
Google Auth работает, телеграм - нет.
Не удается инициализировать бота: Redmine выдает ошибку 500.
В access.log для apache при нажатии на "инициализировать бота" вижу:
xx.xx.xx.xx - - [16/Apr/2017:16:17:32 +0300] "POST /redmine_2fa/bot/init HTTP/1.1" 500 1176 "https://xxxxx.xxxxxxxxxx.ru/settings/plugin/redmine_2fa" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"

Подскажите, пожалуйста, что не так? В какой лог смотреть, чтобы увидеть причину проблемы?

**Comment by olemskoi** [comment]
Попробуйте посмотреть в production.log.

**Comment by muradurm** [comment]
Спасибо.

Там вот что появляется при попытке инициализации.

Started POST "/redmine_2fa/bot/init" for xx.xx.xx.xx at 2017-04-16 17:15:48 +0300
Processing by OtpBotController#create as HTML
  Parameters: {"authenticity_token"=>"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=="}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 39ms (ActiveRecord: 29.2ms)

NameError (uninitialized constant OtpBotController::MultiJson):
  plugins/redmine_2fa/app/controllers/otp_bot_controller.rb:35:in `rescue in set_bot'
  plugins/redmine_2fa/app/controllers/otp_bot_controller.rb:33:in `set_bot'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

В чем может быть проблема?

**Comment by olemskoi** [comment]
Вы установили все неободимые плагины по инструкции? Redmine_telegram_common?
Версии - последние из git?

**Comment by muradurm** [comment]
> Вы установили все неободимые плагины по инструкции? 
да
> Redmine_telegram_common?
да. Бота создал.
> Версии - последние из git?
да, git clone делал.
Ruby был версии 2.2, поставил 2.3. 

Все остальное работает без проблем, включая Google Auth. SMS не включал.

**Comment by olemskoi** [comment]
Покажите ls -laF plugins

**Comment by olemskoi** [comment]
И еще: какой версии redmine?

**Comment by muradurm** [comment]
redmine@xxxxxx:~/redmine$ ls -laF plugins/
total 56
drwxrwxr-x 14 redmine redmine 4096 Apr 16 17:09 ./
drwxrwxr-x 18 redmine redmine 4096 Apr 16 13:08 ../
drwxrwxr-x  6 redmine redmine 4096 Mar  7 06:18 quick_view/
drwxrwxr-x  9 redmine redmine 4096 Apr 16 13:37 redmine_2fa/
drwxrwxr-x 10 redmine redmine 4096 Oct 30 01:39 redmine_banner/
drwxrwxr-x  7 redmine redmine 4096 Apr  5 19:58 redmine_custom_auto_complete/
drwxrwxr-x  4 redmine redmine 4096 Oct 11  2016 redmine_home_page_redirector/
drwxrwxr-x  7 redmine redmine 4096 Oct 16 03:35 redmine_impersonate/
drwxrwxr-x 10 redmine redmine 4096 Mar 23 18:21 redmine_issue_badge/
drwxrwxr-x  8 redmine redmine 4096 Apr  8  2016 redmine_issue_favicon/
drwxrwxr-x  8 redmine redmine 4096 Mar  7 05:32 redmine_lightbox2/
drwxrwxr-x  7 redmine redmine 4096 Oct 30 01:38 redmine_login_attempts_limit/
drwxrwxr-x  8 redmine redmine 4096 Apr 16 13:41 redmine_telegram_common/
drwxrwxr-x  6 redmine redmine 4096 Apr  5 21:28 redmine_zxcvbn/

redmine v3.3.3

**Comment by olemskoi** [comment]
Миграции плагинов запустили?

**Comment by muradurm** [comment]
да, конечно.

**Comment by muradurm** [comment]
Больше информации:
Ubuntu 14.04 32-bit

Environment:
  Redmine version                3.3.3.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [i386-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  full_text_search               0.4.0
  quick_view                     0.3.0
  redmine_2fa                    1.3.2
  redmine_banner                 0.1.2
  redmine_custom_auto_complete   0.0.1
  redmine_home_page_redirector   0.0.1
  redmine_impersonate            0.9.0
  redmine_issue_badge            0.0.5
  redmine_issue_favicon          0.0.1
  redmine_lightbox2              0.3.2
  redmine_login_attempts_limit   0.1.0
  redmine_telegram_common        0.0.15
  redmine_zxcvbn                 1.0.0

Включил в логах apache LogLevel debug: ошибок не увидел.
Папка /opt/redmine/redmine/log/redmine_2fa пустая.

SSL-сертификат полноценный, не самозаверенный (not self signed).

Вот настройки сайта для apache (/etc/apache2/sites-enabled/default-ssl.conf)

<IfModule mod_ssl.c>
        <VirtualHost _default_:443>
                ServerAdmin xxxxxx
                ServerName xxxxxxxx

                DocumentRoot /var/www/html/redmine
                SSLEngine on

                SSLCertificateFile /xxx/xxxx
                SSLCertificateKeyFile      /xxx/xxxx

                <FilesMatch "\.(cgi|shtml|phtml|php)$">
                                SSLOptions +StdEnvVars
                </FilesMatch>

                <Directory /var/www/html/redmine>
                        RailsBaseURI /redmine
                        PassengerResolveSymlinksInDocumentRoot on
                </Directory>

                SSLCertificateChainFile /xxx/xxxx
        </VirtualHost>
</IfModule>

**Comment by constXife** [comment]
Добрый день, muradurm!

Прошу прощения за долгий ответ. Попробуйте обновить плагин из git develop ветки, перезапустить redmine и снова посмотреть будет ли ошибка. Если она возникнет, то ошибка появится в логах (мы поправили момент, что ошибка в лог не писалась)

**Comment by constXife** [comment]
Задачу пока закрою, если проблема возникнет снова — пишите.
