### ISSUE TITLE
Предложение: Сделайте опцию отключения определенных 2FA

### ISSUE THREAD

**Issue by CHERTS** [centosadmin/redmine_2fa#3]
Хороший плагин, но хочется чтобы можно было выбирать какие методы 2FA доступны пользователям. Например мне не нужны Телеграм и СМС, поэтому и не нужно их показывать, а сразу переходить к GAuth с запросом кода.

**Comment by olemskoi** [comment]
Сделаем.

**Comment by CHERTS** [comment]
Спасибо, буду ждать.

**Comment by arturtr** [comment]
Готово

**Comment by CHERTS** [comment]
Спасибо огромное!
