### ISSUE TITLE
unable to install redmine_2fa on redmine 3.3.3

### ISSUE THREAD

**Issue by mcolomboid** [centosadmin/redmine_2fa#31]
Hello, i'm trying to install the redmine 2fa plugins.
i'm following the README, after the bundle command ( all goes right ), when i'm trying to execute bin/rake redmine:plugins:migrate, i'm getting this syntax error:

 
>root@redmine:/opt/bitnami/apps/redmine/htdocs# bin/rake redmine:plugins:migrate RAILS_ENV=production
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:26: warning: else without rescue is useless
rake aborted!
SyntaxError: /opt/bitnami/apps/redmine/htdocs/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:19: syntax error, unexpected '.'
      case user&.auth_source&.auth_method_name
                 ^
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:22: syntax error, unexpected keyword_when, expecting keyword_end
      when 'SMS'
          ^
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:38: syntax error, unexpected keyword_end, expecting end-of-input
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_2fa/init.rb:12:in `block (3 levels) in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_2fa/init.rb:11:in `each'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_2fa/init.rb:11:in `block (2 levels) in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_2fa/init.rb:10:in `each'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_2fa/init.rb:10:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
>

any clue? thanks

**Comment by olemskoi** [comment]
Hello,

What version of ruby do you use?

**Comment by mcolomboid** [comment]
Hello,
sorry, my fault. I'm using the bitname redmine image, with ruby 2.1
I've tried with ruby 2.3, all fine
