### ISSUE TITLE
Install error Redmine 3.4.2

### ISSUE THREAD

**Issue by x-itec** [centosadmin/redmine_2fa#36]
bundle exec rake redmine_2fa:common:migrate

bundle exec rake redmine_2fa:common:migrate
/var/www/html/redmine/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:26: warning: else without rescue is useless
rake aborted!
SyntaxError: /var/www/html/redmine/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:19: syntax error, unexpected '.'
      case user&.auth_source&.auth_method_name
                 ^
/var/www/html/redmine/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:22: syntax error, unexpected keyword_when, expecting keyword_end
      when 'SMS'
          ^
/var/www/html/redmine/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:38: syntax error, unexpected keyword_end, expecting end-of-input
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:457:in `load'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:457:in `block in load_file'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:647:in `new_constants_in'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:456:in `load_file'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:354:in `require_or_load'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:317:in `depend_on'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:233:in `require_dependency'
/var/www/html/redmine/plugins/redmine_2fa/init.rb:12:in `block (3 levels) in <top (required)>'
/var/www/html/redmine/plugins/redmine_2fa/init.rb:11:in `each'
/var/www/html/redmine/plugins/redmine_2fa/init.rb:11:in `block (2 levels) in <top (required)>'
/var/www/html/redmine/plugins/redmine_2fa/init.rb:10:in `each'
/var/www/html/redmine/plugins/redmine_2fa/init.rb:10:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `instance_exec'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `call'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `block in simple'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `each'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/var/www/html/redmine/config/environment.rb:14:in `<top (required)>'
/var/www/html/redmine/plugins/periodictask/lib/tasks/periodictask.rake:7:in `require'
/var/www/html/redmine/plugins/periodictask/lib/tasks/periodictask.rake:7:in `<top (required)>'
/var/www/html/redmine/lib/tasks/redmine.rake:194:in `load'
/var/www/html/redmine/lib/tasks/redmine.rake:194:in `block in <top (required)>'
/var/www/html/redmine/lib/tasks/redmine.rake:194:in `each'
/var/www/html/redmine/lib/tasks/redmine.rake:194:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/engine.rb:658:in `load'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/engine.rb:658:in `each'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/engine.rb:658:in `run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/application.rb:452:in `run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/engine.rb:453:in `load_tasks'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/var/www/html/redmine/Rakefile:7:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

**Comment by constXife** [comment]
Hi, @x-itec! It's look like your ruby is 2.2, but plugin requirement is version 2.3 or higher.

**Comment by x-itec** [comment]
Ok, sorry - tnx I will give it a try
