### ISSUE TITLE
error while initializing the bot

### ISSUE THREAD

**Issue by nixkn** [centosadmin/redmine_2fa#38]
Hello,

Im getting an error while initializing the bot. 

NameError (uninitialized constant OtpBotController::MultiJson):
  plugins/redmine_2fa/app/controllers/otp_bot_controller.rb:35:in `rescue in set_bot'
  plugins/redmine_2fa/app/controllers/otp_bot_controller.rb:33:in `set_bot'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by constXife** [comment]
@nixkn, Hi! Sorry for slow answer. Try to update plugin from develop. It should help.

**Comment by constXife** [comment]
I will close the issue. Make new issue if problem will occur again or you have another question. Thanks!
