### ISSUE TITLE
Problem during upgrade to redmine 3.4

### ISSUE THREAD

**Issue by mcolomboid** [centosadmin/redmine_2fa#39]
Hello,
I have a problem during the upgrade of redmine from version 3.3.3 to 3.4.2.
I'm using the redmine_2fa plugin, version: 1.3.2 for 2FA
After the upgrade I'm able to login using the username and password, but when i try to insert the authorization code (2FA) I always receive "Wrong authorization code" though the code is right.
With the same code I am able to login using redmine 3.3.3

I'm using a test environment, that is a clone based on the production environment. The only change is the redmine url.
I'm using Ruby version 2.3.1-p112 and Rails 4.2.7.1. 

I did not find a documentation about the upgrade, maybe i can do it
Ask me if you need more logs

Thanks

**Comment by constXife** [comment]
@mcolomboid, Hi! What method do you using for 2FA? Google? Telegram?

**Comment by mcolomboid** [comment]
Hello @constXife,
thanks so much for the reply. I'm using 2FA with google auth.
Seems that the problem is related with the redmine url. 
Is it possible that the token is valid only with the same url? 
Maybe when i change the url of redmine i need to reset the 2fa token

**Comment by constXife** [comment]
Ah, I see. If redmine url changed, then you should renew your Google Auth entry. Because it based on it. You can go to your profile and click on reset 2fa link. Then logout from redmine, login again.

**Comment by mcolomboid** [comment]
Thanks so much!
