### ISSUE TITLE
Issue while running migrate

### ISSUE THREAD

**Issue by drakesjoy** [centosadmin/redmine_2fa#4]
Hello,

Im getting below error while im trying to migrate 2fa. 

Redmine-3.3.0
# Ruby -2.3

Migrating redmine_2fa (Redmine 2FA)...
== 1 CreateTelegramAccounts: migrating ========================================
-- create_table(:redmine_2fa_telegram_accounts)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Cannot add foreign key constraint: ALTER TABLE `redmine_2fa_telegram_accounts` ADD CONSTRAINT `fk_rails_52bb5e5f07`
FOREIGN KEY (`user_id`)
  REFERENCES `users` (`id`)
/home/pm/rails_apps/redmine/plugins/redmine_2fa/db/migrate/001_create_telegram_accounts.rb:3:in `change'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:481:in`migrate_plugin'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:453:in `migrate'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:467:in`block in migrate'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:466:in `each'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:466:in`migrate'
/home/pm/rails_apps/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
ActiveRecord::StatementInvalid: Mysql2::Error: Cannot add foreign key constraint: ALTER TABLE`redmine_2fa_telegram_accounts`ADD CONSTRAINT`fk_rails_52bb5e5f07`
FOREIGN KEY (`user_id`)
  REFERENCES`users`(`id`)
/home/pm/rails_apps/redmine/plugins/redmine_2fa/db/migrate/001_create_telegram_accounts.rb:3:in`change'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:453:in`migrate'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:466:in`each'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:466:in `migrate'
/home/pm/rails_apps/redmine/lib/tasks/redmine.rake:127:in`block (3 levels) in <top (required)>'
Mysql2::Error: Cannot add foreign key constraint
/home/pm/rails_apps/redmine/plugins/redmine_2fa/db/migrate/001_create_telegram_accounts.rb:3:in `change'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:481:in`migrate_plugin'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:453:in `migrate'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:467:in`block in migrate'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:466:in `each'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:466:in`migrate'
/home/pm/rails_apps/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
# (See full trace by running task with --trace)

**Comment by arturtr** [comment]
Do you have `users` table? Is it clean installation? Or you install it on already worked system?

Try to google about "MySQL Cannot Add Foreign Key Constraint"

It looks like problems with you DB.

I develop this plugin with PostgreSQL. I will try it with MySQL later if you can't to find solution.
